### ISSUE TITLE
hfc_favicons - enable: false is being ignored in version 1.2.0 - hfc generates icons anyway

### ISSUE THREAD

**Issue by jennifer-shehane** [mamboer/hexo-filter-cleanup#11]
This isn't necessarily a *bug* per se, but it was definitely unexpected behavior to update from 1.1.0 to 1.2.0 and have a breaking change.

The favicon that I have set up in our `swig` template is not longer displaying: https://github.com/cypress-io/cypress-documentation/blob/develop/themes/cypress/layout/partial/head.swig#L21 

Instead another image is displaying as our favicon. It looks to be the image that is configured as our logo. I have no idea how this is now our favicon. https://github.com/cypress-io/cypress-documentation/blob/develop/_config.yml#L18

I suspect it's due to some changes made from this commit https://github.com/mamboer/hexo-filter-cleanup/commit/d66e21c although I am still tracking it down.

Furthermore, we have `hfc_favicons` set to `enable: false`, so none of this work should even be done with hexo-filter-cleanup as I understand it. 

Granted, we are doing some weird things by assigning hexo config within the `initHexo` function.

**Comment by jennifer-shehane** [comment]
Verified that downgrading to 1.1.0 fixes my issue. 

I also tried to update to use the `hfc_favicons` and set the `src` to be a different location than the default. It also ignored any config I passed here. It seems to just always apply the default config settings regardless of what I pass to `hfc_favicons` in version 1.2.0

**Comment by aispin** [comment]
Hi Jennifer,

The `favicons` feature of `hexo-filter-cleanup` is that we can generate the [favicon staffs](https://github.com/o2team/o2team.github.io/blob/v2/source/_data/favicons.json) automatically by specifying a favicon image. And the default favicon image is being configured as `img/logo.png` which happens to be same as your site's logo configuration.

In your case, since you have specified a favicon manually in the `head.swig`, you should and it's safe to disable the `favicons` feature by setting `enable` to `false`.

**Comment by aispin** [comment]
If you do need the `favicons` feature, you can custom favicon image's configuration by setting the `src` property. 

Pls notice that you should put the custom favicon image in the theme's source folder, like this one,

https://github.com/mamboer/hfc_demo/blob/master/themes/maupassant/source/img/my_custom_favicon.png

For further explanation, take a look at this simple demo: https://github.com/mamboer/hfc_demo

Thanks and best regards.

**Comment by jennifer-shehane** [comment]
We have `hfc_favicons` set to `enable: false`, this is my reasoning for the open issue. This option successfully disabled hfc from generating the favicons in version 1.1.0, but when upgrading to 1.2.0 our setting of `hfc_favicons: {enable: false}` is being ignored. 

Our hfc config can be found here: https://github.com/cypress-io/cypress-documentation/blob/f834460b3bbbedae16befdee53f45aeab49c5682/index.js#L26

**Comment by jennifer-shehane** [comment]
Thanks, this update fixed it
