### ISSUE TITLE
Cannot read property 'length' of undefined during cleanup

### ISSUE THREAD

**Issue by jennifer-shehane** [mamboer/hexo-filter-cleanup#12]
I am encountering a new error after updating to version 1.2.1. 

During running `hexo-filter-cleanup`

```
Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'length' of undefined
    at utils.isFileChanged.then.yes (/root/cypress-documentation/node_modules/hexo-filter-cleanup/lib/js.js:35:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) }
reason:  TypeError: Cannot read property 'length' of undefined
    at utils.isFileChanged.then.yes (/root/cypress-documentation/node_modules/hexo-filter-cleanup/lib/js.js:35:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

Link to our CI logs that failed: https://circleci.com/gh/cypress-io/cypress-documentation/12752

**Comment by aispin** [comment]
Mmm, seems that it's the same issue as #8 

Try to remove the following empty configurations from `hfc_js`,

```
 output:
 compress:
```

In your case it is,

```
output: {},
compress: {},
```

I will dig into this issue later on.

**Comment by aispin** [comment]
Hi, i've figured it out, `uglify-js` doesn't accept an empty `output` configuration anymore, 
pls remove the `output` option in your code and upgrade `hexo-filter-cleanup` to version 1.2.2.

Cheers.

**Comment by jennifer-shehane** [comment]
Thanks 👍
