### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by acyuta108** [mamboer/hexo-filter-cleanup#3]
> ERROR Plugin load failed: hexo-filter-cleanup
> Error: Cannot find module 'lodash'
> ...
> at Object.<anonymous> (/Users/matea/Documents/mateayoga.com/node_modules/hexo-filter-cleanup/lib/useref.js:9:31)

I noticed you require it in useref.js but it's not included in the plugin's package.json.

I installed it into my project's package.json and it works now.

I guess you can either add it to the package.json or add the requirement in the docs for users to install.

Thanks for the good work ;)

**Comment by aispin** [comment]
Hi, 
I've removed the dependence of `lodash` now, thanks for your response.
