### ISSUE TITLE
Generating code for favicons

### ISSUE THREAD

**Issue by ghost** [mamboer/hexo-filter-cleanup#4]
Hello! I've gotten the icons themselves generated, but how do I generate the HTML for it? I've found the html.json file in the favicons node module, but that'd be a bit of a pain to extract and it's not really a good method as you'd have to redo it all if there's changes breaking it.

**Comment by aispin** [comment]
@Krakob 
hi,
HTML generation has been supported from v1.2.0, `hexo-filter-cleanup` will generate a `favicons.json` file in the `_data` folder, and you can use it as your site's data.

Take a look at the example for usage details,

https://github.com/o2team/o2team.github.io/blob/v2/source/_data/favicons.json
https://github.com/o2team/o2team.github.io/blob/v2/themes/lattice/layout/_partial/common/favicons.swig
