### ISSUE TITLE
Unhandled Rejection at Promise

### ISSUE THREAD

**Issue by jennifer-shehane** [mamboer/hexo-filter-cleanup#6]
I am getting this error during my hexo-filter-cleanup in version 1.1.0. Rolled back to 1.0.7 and issue went away. 

```
Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'length' of undefined
    at utils.isFileChanged.then.yes (--/node_modules/hexo-filter-cleanup/lib/js.js:35:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) }
reason:  TypeError: Cannot read property 'length' of undefined
    at utils.isFileChanged.then.yes (--/node_modules/hexo-filter-cleanup/lib/js.js:35:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jennifer-shehane** [comment]
We do setup our config a bit differently, but we catch unhandled Promises. Our code: https://github.com/cypress-io/cypress-documentation/blob/develop/index.js#L1

**Comment by aispin** [comment]
Hi,
We've upgraded uglifyjs to V3 in version 1.1.0, be sure to check the `hfc_js` options following the latest [uglifyjs](https://github.com/mishoo/UglifyJS2#minify-options) options.

If still have problems, could you pls provide me a minimal example for locally debug.

Thanks.

**Comment by ai0** [comment]
@jennifer-shehane Hi, I have checked your code, you need change `output: null` to `output: {}` in L32, not compress, compress option can be null, that's fine.

**Comment by jennifer-shehane** [comment]
@ai0 Yeah, I did update that line and am getting another SyntaxError. Anyway, likely it's just related to my set up somewhere, so I'll close this.
