### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by dazkarieh** [mamboer/hexo-filter-cleanup#7]
xxxiMac:ian root# npm install hexo-filter-cleanup --save
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> phantomjs-prebuilt@2.1.16 install /Users/dazkarieh/Public/ian/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT 52.216.225.16:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-06-23T13_53_28_185Z-debug.log

**Comment by tomap** [comment]
Hi,

I do believe your problem is just an HTTP connection issue. Could you check that you where connected at that time?
Otherwise, this is related to this package: phantomjs-prebuilt
Go there an ask for help :)

**Comment by aispin** [comment]
@dazkarieh,
1. Try one more time for installing
2. Setup a custom `PHANTOMJS_CDNURL`  ENV variable in your `.zshrc` file

```
export PHANTOMJS_CDNURL=https://npm.taobao.org/dist/phantomjs
```
