### ISSUE TITLE
Fail to process js file

### ISSUE THREAD

**Issue by zklhp** [mamboer/hexo-filter-cleanup#8]
Due to `result.code.length` from

https://github.com/mamboer/hexo-filter-cleanup/blob/14498904dc2534d33917a171425c7407f45a6c66/lib/js.js#L35

The error message looks like

> (node:18188) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at utils.isFileChanged.then.yes (C:\msys64\home\Kel\repo\hexo-blog\node_modules\hexo-filter-cleanup\lib\js.js:35:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Could you please have a look at this?

Thank you.

**Comment by HarborZeng** [comment]
same err to me @mamboer

**Comment by aispin** [comment]
@zklhp @HarborZeng 
hi guys, what's your system os and can you provide me a sample project ?

Thanks.

**Comment by HarborZeng** [comment]
> @zklhp @HarborZeng
> hi guys, what's your system os and can you provide me a sample project ?
> 
> Thanks.

I gave up using this

**Comment by aispin** [comment]
Can't reproduce this issue on both macos 10.14 and windows 10（using git bash, test on this [hexo project](https://github.com/o2team/o2team.github.io/)）。

**Comment by zklhp** [comment]
Yes, it is negligible, because the JS files were optimized. Only the report was affected. However, I can 100% reproduce it. I am using Node v11.14.0 on MS-Windows 8.1, and the theme is [maupassant-hexo](https://github.com/tufu9441/maupassant-hexo). The JS files were

https://github.com/tufu9441/maupassant-hexo/blob/master/source/js/donate.js

https://github.com/tufu9441/maupassant-hexo/blob/master/source/js/gitment.browser.js

I am still using this plugin. It is great. Thank you for your work.

**Comment by aispin** [comment]
@zklhp 

Still no luck that i cannot reproduce the issue,

Take a look at this demo using the [maupassant](https://github.com/tufu9441/maupassant-hexo) theme:

https://github.com/mamboer/hfc_demo/

Which terminal did you use in your case, could you try the [Git Bash](https://gitforwindows.org/) terminal ?

**Comment by zklhp** [comment]
@mamboer Thank you. I found the devil. In my `_config.yml`, remove 

```yaml
  output:
  compress:
```

and all goes well.
